"""scenario-spine: one scenario spine for autonomous driving.

Five products over a single intermediate representation:

    generate  -> a scenario from a parametric query, exported to OpenSCENARIO / SUMO
    odd       -> ODD coverage decided in three-valued logic (sat / violated / unknown)
    difficulty-> a physically grounded 1-10 score with attributed sources
    labelqc   -> what is wrong with an annotation set, per error class
    fleet     -> dispatch and charging, with the gap to the exact optimum measured
    assurance -> a GSN safety case emitted from the evidence above

Standard library only. No GPU. Every number in the README is regenerated by
bench/experiment.py.
"""

__version__ = "0.1.0"
